POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "name": "tony",
    "phoneNumber": "324235435",
    "email": "tony@gmail.com",
    "password": "12345"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "thao@gmail.com",
    "password": "12345"
}