GET http://localhost:3000/animals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQxZWI4ZDQ4YmJiOTUzMzFhOGM4ZDQiLCJuYW1lIjoidG9ueSIsInBob25lTnVtYmVyIjoiMzI0MjM1NDM1IiwiZW1haWwiOiJ0b255QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiIiwiY3JlYXRlZEF0IjoiMjAyMy0wNC0yMVQwMTo0OTowMS43MTBaIiwidXBkYXRlZEF0IjoiMjAyMy0wNC0yMVQwMTo0OTowMS43MTBaIiwiX192IjowLCJpYXQiOjE2ODIxMjUwMTF9.aV6BBxKN8bU4Pt5yRYL1RA5FGr2rSAICVKejFxA3VL4

###
GET http://localhost:3000/animals?action=listMissingAnimals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQ0NDc2Y2U3MTZlNzZlMTRmODVkZjEiLCJuYW1lIjoidHVuZyIsImFkZHJlc3MiOnsibG9jYXRpb24iOltdfSwicGhvbmVOdW1iZXIiOiIzNDIzNCIsImVtYWlsIjoidHVuZ0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiIsImNyZWF0ZWRBdCI6IjIwMjMtMDQtMjJUMjA6NDU6MzIuODgxWiIsInVwZGF0ZWRBdCI6IjIwMjMtMDQtMjJUMjA6NDU6MzIuODgxWiIsIl9fdiI6MCwiaWF0IjoxNjgyMjE5NzUyfQ.Hbro1FiwMvlcr2rd7G_DMGLLjrm-H4fAUy-y_H_0HQQ

###
POST http://localhost:3000/animals?action=addMissingAnimal
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQ0NDc2Y2U3MTZlNzZlMTRmODVkZjEiLCJuYW1lIjoidHVuZyIsImFkZHJlc3MiOnsibG9jYXRpb24iOltdfSwicGhvbmVOdW1iZXIiOiIzNDIzNCIsImVtYWlsIjoidHVuZ0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiIsImNyZWF0ZWRBdCI6IjIwMjMtMDQtMjJUMjA6NDU6MzIuODgxWiIsInVwZGF0ZWRBdCI6IjIwMjMtMDQtMjJUMjA6NDU6MzIuODgxWiIsIl9fdiI6MCwiaWF0IjoxNjgyMjE5NzUyfQ.Hbro1FiwMvlcr2rd7G_DMGLLjrm-H4fAUy-y_H_0HQQ
Content-Type: application/json

{
  "category": "Cat 5",
  "name": "Fluffy",
  "breed": "Persian",
  "sex": "female",
  "age": 4,
  "color": "white",
  "weight": 4.5,
  "loss_date": "2022-03-10",
  "image": []
}

###
GET http://localhost:3000/animals?action=listFoundAnimalS
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQxZWI4ZDQ4YmJiOTUzMzFhOGM4ZDQiLCJuYW1lIjoidG9ueSIsInBob25lTnVtYmVyIjoiMzI0MjM1NDM1IiwiZW1haWwiOiJ0b255QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiIiwiY3JlYXRlZEF0IjoiMjAyMy0wNC0yMVQwMTo0OTowMS43MTBaIiwidXBkYXRlZEF0IjoiMjAyMy0wNC0yMVQwMTo0OTowMS43MTBaIiwiX192IjowLCJpYXQiOjE2ODIxMjUwMTF9.aV6BBxKN8bU4Pt5yRYL1RA5FGr2rSAICVKejFxA3VL4

###
POST http://localhost:3000/animals?action=addFoundAnimal
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQxZWI4ZDQ4YmJiOTUzMzFhOGM4ZDQiLCJuYW1lIjoidG9ueSIsInBob25lTnVtYmVyIjoiMzI0MjM1NDM1IiwiZW1haWwiOiJ0b255QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiIiwiY3JlYXRlZEF0IjoiMjAyMy0wNC0yMVQwMTo0OTowMS43MTBaIiwidXBkYXRlZEF0IjoiMjAyMy0wNC0yMVQwMTo0OTowMS43MTBaIiwiX192IjowLCJpYXQiOjE2ODIxMjUwMTF9.aV6BBxKN8bU4Pt5yRYL1RA5FGr2rSAICVKejFxA3VL4
Content-Type: application/json

{
  "category": "Cat",
  "name": "Fluffy",
  "breed": "Persian",
  "sex": "female",
  "age": 4,
  "color": "white",
  "weight": 4.5,
  "found_date": "2022-03-10",
  "image": []
}

###
GET http://localhost:3000/animals?action=listAdoptAnimals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQxZWI4ZDQ4YmJiOTUzMzFhOGM4ZDQiLCJuYW1lIjoidG9ueSIsInBob25lTnVtYmVyIjoiMzI0MjM1NDM1IiwiZW1haWwiOiJ0b255QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiIiwiY3JlYXRlZEF0IjoiMjAyMy0wNC0yMVQwMTo0OTowMS43MTBaIiwidXBkYXRlZEF0IjoiMjAyMy0wNC0yMVQwMTo0OTowMS43MTBaIiwiX192IjowLCJpYXQiOjE2ODIxMjUwMTF9.aV6BBxKN8bU4Pt5yRYL1RA5FGr2rSAICVKejFxA3VL4

###
POST http://localhost:3000/animals?action=addAdoptAnimal
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQxZWI4ZDQ4YmJiOTUzMzFhOGM4ZDQiLCJuYW1lIjoidG9ueSIsInBob25lTnVtYmVyIjoiMzI0MjM1NDM1IiwiZW1haWwiOiJ0b255QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiIiwiY3JlYXRlZEF0IjoiMjAyMy0wNC0yMVQwMTo0OTowMS43MTBaIiwidXBkYXRlZEF0IjoiMjAyMy0wNC0yMVQwMTo0OTowMS43MTBaIiwiX192IjowLCJpYXQiOjE2ODIxMjUwMTF9.aV6BBxKN8bU4Pt5yRYL1RA5FGr2rSAICVKejFxA3VL4
Content-Type: application/json

{
  "category": "Cat A",
  "name": "Fluffy",
  "breed": "Persian",
  "sex": "female",
  "age": 4,
  "color": "white",
  "weight": 4.5,
  "adopt_date": "2022-04-10",
  "adopted_user": {
    "_id": "6441eb8d48bbb95331a8c8d4",
    "name": "Thao",
    "email": "",
    "address": {},
    "phoneNumber": ""
  },
  "image": []
}

###
GET http://localhost:3000/animals/644339038d713f17425a3ba1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQxZWI4ZDQ4YmJiOTUzMzFhOGM4ZDQiLCJuYW1lIjoidG9ueSIsInBob25lTnVtYmVyIjoiMzI0MjM1NDM1IiwiZW1haWwiOiJ0b255QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiIiwiY3JlYXRlZEF0IjoiMjAyMy0wNC0yMVQwMTo0OTowMS43MTBaIiwidXBkYXRlZEF0IjoiMjAyMy0wNC0yMVQwMTo0OTowMS43MTBaIiwiX192IjowLCJpYXQiOjE2ODIxMjUwMTF9.aV6BBxKN8bU4Pt5yRYL1RA5FGr2rSAICVKejFxA3VL4

###
PATCH http://localhost:3000/animals/644339038d713f17425a3ba1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQxZWI4ZDQ4YmJiOTUzMzFhOGM4ZDQiLCJuYW1lIjoidG9ueSIsInBob25lTnVtYmVyIjoiMzI0MjM1NDM1IiwiZW1haWwiOiJ0b255QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiIiwiY3JlYXRlZEF0IjoiMjAyMy0wNC0yMVQwMTo0OTowMS43MTBaIiwidXBkYXRlZEF0IjoiMjAyMy0wNC0yMVQwMTo0OTowMS43MTBaIiwiX192IjowLCJpYXQiOjE2ODIxMjUwMTF9.aV6BBxKN8bU4Pt5yRYL1RA5FGr2rSAICVKejFxA3VL4
Content-Type: application/json

{
    "name": "Tom",
    "breed": "Persian 1",
    "sex": "male",
    "age": 3,
    "color": "red",
    "weight": 5
}

###
DELETE  http://localhost:3000/animals/64443c55450a81d288ad0d09
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQxZWI4ZDQ4YmJiOTUzMzFhOGM4ZDQiLCJuYW1lIjoidG9ueSIsInBob25lTnVtYmVyIjoiMzI0MjM1NDM1IiwiZW1haWwiOiJ0b255QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiIiwiY3JlYXRlZEF0IjoiMjAyMy0wNC0yMVQwMTo0OTowMS43MTBaIiwidXBkYXRlZEF0IjoiMjAyMy0wNC0yMVQwMTo0OTowMS43MTBaIiwiX192IjowLCJpYXQiOjE2ODIxMjUwMTF9.aV6BBxKN8bU4Pt5yRYL1RA5FGr2rSAICVKejFxA3VL4
Content-Type: application/json